
# NMAKE makefile, creates IDECHECK.EXE and IDECKVDD.DLL
# using jwasm & jwlink
# uses HXDEV for
#   - idecheck: stub loadpex.bin ( contains HDPMI32 )
#   - ideckvdd: import libraries dkrnl32, duser32 & ntvdm; win32 include files

NAME=IDECHECK
NAME2=IDECKVDD

HXDIR=\hx

!ifndef MASM
MASM=0
MSLINK=0
!else
MSLINK=1
!endif

!ifndef DEBUG
DEBUG=0
!endif

!if $(DEBUG)
OUTDIR=DEBUG
AOPTD=-Zi -D_DEBUG
LOPTD=debug c op cvp
!else
OUTDIR=RELEASE
!endif

LIBS2=LIBPATH $(HXDIR)\Lib Library dkrnl32.lib, duser32.lib, ntvdm.lib

ALL: $(OUTDIR) $(OUTDIR)\$(NAME).EXE $(OUTDIR)\$(NAME2).DLL

$(OUTDIR):
	@mkdir $(OUTDIR)

$(OUTDIR)\$(NAME).exe: $(OUTDIR)\$(NAME).obj Makefile
	@jwlink.exe $(LOPTD) format windows pe hx file $(OUTDIR)\$(NAME).obj op quiet,map=$(OUTDIR)\$(NAME).map, stub=$(HXDIR)\bin\LOADPEX.BIN, stack=0x1000, dosseg

$(OUTDIR)\$(NAME).obj: src\$(NAME).asm
	@jwasm.exe -nologo -coff -c -Fl$* -Fo$* -Sg $(AOPTD) src\$(NAME).asm

$(OUTDIR)\$(NAME2).dll: $(OUTDIR)\$(NAME2).obj Makefile src\$(NAME2).lbc
	@jwlink.exe $(LOPTD) format windows pe dll file $(OUTDIR)\$(NAME2).obj name $*.DLL $(LIBS2) op quiet,MAP=$(OUTDIR)\$(NAME2).map @src\$(NAME2).lbc

$(OUTDIR)\$(NAME2).obj: src\$(NAME2).asm
	@jwasm.exe -nologo -coff -c -Fl$* -Fo$* -Sg $(AOPTD) -I$(HXDIR)\include src\$(NAME2).asm

clean:
	erase $(OUTDIR)\*.obj
	erase $(OUTDIR)\*.exe
	erase $(OUTDIR)\*.dll
	erase $(OUTDIR)\*.lst
	erase $(OUTDIR)\*.map
